#!/usr/bin/env python
# encoding: utf-8
# Author: Shawn Roche
# Date: 3/16/2015
#########################
import csv
import argparse
import keyring
import os
from datetime import date, time

from apperianapi import apperian
import progress


def main():
    base_path = os.path.expanduser('~/.ease_utils/del_orgs')
    if not os.path.isfile(base_path):
        os.makedirs(base_path)

    parser = argparse.ArgumentParser(prog='Bulk Org Delete', usage='ease_del_orgs --orgs 123,456,789 --env na')
    parser.add_argument('--env', default='default', help='Environment to run against. EX: na, eu')
    parser.add_argument('--orgs', default=False, required=True,
                        help='Comma separated list of org IDs or path to a csv containing the target org IDs')
    parser.add_argument('--user', default='help@apperian.com',
                        help='Admin account that has the permissions to delete the target orgs')
    parser.add_argument('--pw', default=keyring.get_password('ease_ua', 'help@apperian.com'),
                        help='Password for admin user you are using')
    parser.add_argument('--verbose', default=False, action='store_true')

    args = parser.parse_args()
    success, failed = [], []
    today = date.today()

    with open('{}/whitelist.csv'.format(base_path), 'rb') as f:
        whitelist = []
        contents = csv.reader(f, delimiter=',', quotechar='"')
        for row in contents:
            whitelist.append(row[0])

    if '.csv' in args.orgs:
        with open(args.orgs, 'rb') as f:
            org_ids = []
            contents = csv.reader(f, delimiter=',', quotechar='"')
            for row in contents:
                if row[1] not in whitelist:
                    org_ids.append(row)
    else:
        org_ids = [['n/a', x] for x in args.orgs.split(',')]

    total = len(org_ids)
    raw_input('About to delete {} orgs from EASE. Press key to continue.'.format(str(total)))

    ease = apperian.Pyapi(args.user, args.pw, region=args.env, verbose=args.verbose)
    progress_bar = progress.Bar(total)

    count, auth_fail = 0, 0
    while org_ids and auth_fail < 3:
        delete_request = ease.org_delete(org_ids[-1][1])
        if delete_request['status'] == 401:
            auth_fail += 1
            time.sleep(2)
            ease.auth()
        else:
            count += 1
            progress_bar.update(count)
            attempted_org = org_ids.pop()
            if delete_request['status'] == 200:
                attempted_org.append(today)
                success.append(attempted_org)
            else:
                attempted_org.append(delete_request['result'])
                failed.append(attempted_org)

    if ease.status != 200:
        print 'Re-authentication failed 3 times, there is an issue with the connection to the server.'
        print delete_request
        print 'Remaining orgs have been marked failed.'
        failed.extend(org_ids)

    if failed:
        print '{} failed. Check {}/failed_{}.csv for details\n'.format(len(failed), base_path, today)
        with open('{}/failed_{}.csv'.format(base_path, today), 'wb') as f:
            writer = csv.writer(f)
            writer.writerows(failed)

    if success:
        with open('{}/deleted_master.csv', 'ab') as f:
            writer = csv.writer(f)
            writer.writerows(success)
        with open('{}/deleted_{}.csv'.format(base_path, today), 'ab') as f:
            writer = csv.writer(f)
            writer.writerows(success)

if __name__ == '__main__':
    main()
