#!/usr/bin/env python
# encoding: utf-8
# Author: Shawn Roche
# Date: 7/3/2016
#########################
import csv
import os
import time
from datetime import date
import argparse
import json
import getpass

import progress
import base_class
from apperianapi import apperian
try:
    import keyring
except ImportError:
    keyring = None


class DeleteUsers(base_class.AdminUtilBase):
    def __init__(self):
        base_class.AdminUtilBase.__init__(self, os.path.expanduser('~/.ease_utils/del_users'))

        args = self.get_args()
        self.csv = args['csv']
        self.env = args['env']
        self.org = args['org']
        self.today = date.today()

        self.ease = apperian.Pyapi(args['user'], args['password'], org_psk=self.org, region=self.env, verbose=True)

    def build_list(self):
        with open(self.csv, 'rb') as f:
            reader = csv.DictReader(f)
            for row in reader:
                self.psks.append(row)

        print 'Building list of user PSKs'
        tmp_user_list = self.ease.user.list()
        tmp_user_list = [{'psk': x['psk'], 'user_id': x['id']} for x in tmp_user_list['result'] for y in self.psks
                         if x['id'] == y['User ID']]

        print 'Checking for duplicates'
        psk_list = []
        user_list = []
        for i in tmp_user_list:
            if i['psk'] not in psk_list:
                psk_list.append(i['psk'])
                user_list.append(i)

        if len(tmp_user_list) - len(user_list) != 0:
            print 'Removed {} duplicates'.format(len(tmp_user_list))
        pass

    def delete(self):
        total = len(self.psks)
        raw_input('About to delete {} users from org {} on {}. Press any key to continue.'.format(
            total, self.ease.org_psk, self.env.upper()))

        count, auth_fail = 0, 0
        progress_bar = progress.Bar(total)
        while self.psks and auth_fail < 3:
            target_user = self.psks[-1]
            delete_request = self.ease.user.delete(target_user['psk'])

            if delete_request['status'] == 401:
                auth_fail += 1
                time.sleep(2)
                self.ease.auth()
            else:
                count += 1
                auth_fail = 0
                target_user = self.psks.pop()
                if delete_request['status'] == 200:
                    self.success.append([self.org, target_user['user_id'], self.today])
                else:
                    self.failed.append([target_user['user_id'], delete_request['result']])

                progress_bar.update(count)

        if self.ease.status != 200:
            print 'Re-authentication failed 3 times, there is an issue with the connection to the server.'
            print delete_request
            print 'Remaining users have been marked failed.'

            self.failed.extend(self.psks)

    def get_args(self):
        with open('{}/config.json'.format(self.app_path)) as f:
            loaded_args = json.load(f)

        parser = argparse.ArgumentParser(prog='Bulk User Delete',
                                         usage='python delete_users.py --org ORG_NAME --csv user_ids.csv')

        parser.add_argument('--org', default=False,
                            help='PSK of the organization to delete users from. If left blank, the org of the '
                                 'credentials you authenticate with will be used')
        parser.add_argument('--env', default='default', help='Environment to run against')
        parser.add_argument('--csv', default='user_ids.csv',
                            help='Path to the csv with user IDs. Default is user_ids.csv')
        parser.add_argument('--user', default=loaded_args['ease_admin'], help='Ease admin password for org or ENV')

        args = vars(parser.parse_args())

        if not args['user']:
            args['user'] = raw_input('Admin Username: ')

        if keyring:
            args['password'] = keyring.get_password('ease_ua', args['user'])
        else:
            args['password'] = getpass.getpass('Admin Password: ')

        return args


def main():
    delete_client = DeleteUsers()

    delete_client.build_list()
    delete_client.delete()
    delete_client.log_results()

if __name__ == '__main__':
    main()
